spring:
  datasource:
    url: jdbc:oracle:thin:@//${ORACLE_HOST:localhost}:1521/${ORACLE_SERVICE_NAME:XEPDB1}
    username: APP
    password: App_1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: APP
    default-schema: APP
    validate-on-migrate: true
    clean-disabled: true