CREATE TABLE EMPLOYEE (
                          ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          FIRST_NAME       VARCHAR2(60)   NOT NULL,
                          SECOND_NAME      VARCHAR2(60),
                          LAST_NAME        VARCHAR2(80)   NOT NULL,
                          MOTHER_LAST_NAME VARCHAR2(80)   NOT NULL,
                          AGE              NUMBER(3)      NOT NULL CHECK (AGE BETWEEN 0 AND 120),
                          GENDER           CHAR(1)        NOT NULL CHECK (GENDER IN ('M','F','O')),
                          BIRTH_DATE       DATE           NOT NULL,
                          POSITION         VARCHAR2(120)  NOT NULL,
                          CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
                          ACTIVE           NUMBER(1)      DEFAULT 1 NOT NULL CHECK (ACTIVE IN (0,1))
);

CREATE INDEX IDX_EMPLOYEE_FIRST_NAME ON EMPLOYEE (FIRST_NAME);
CREATE INDEX IDX_EMPLOYEE_LAST_NAME  ON EMPLOYEE (LAST_NAME);
