INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Juan', 'Carlos', 'Pérez', 'López', 31, 'M', TO_DATE('01-01-1994','DD-MM-YYYY'), 'Senior Developer', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Ana', 'María', 'González', 'Ruiz', 28, 'F', TO_DATE('15-03-1997','DD-MM-YYYY'), 'QA Engineer', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Luis', 'Alberto', 'Hernández', 'Soto', 35, 'M', TO_DATE('22-07-1989','DD-MM-YYYY'), 'DevOps Engineer', 0);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Sofía', 'Fernanda', 'Ramírez', 'Torres', 26, 'F', TO_DATE('10-11-1998','DD-MM-YYYY'), 'Product Manager', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Carlos', 'Eduardo', 'Mendoza', 'Chávez', 42, 'M', TO_DATE('05-05-1983','DD-MM-YYYY'), 'Software Architect', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('María', 'José', 'Rodríguez', 'Vargas', 30, 'F', TO_DATE('12-09-1994','DD-MM-YYYY'), 'Data Analyst', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Diego', 'Armando', 'Sánchez', 'Navarro', 33, 'M', TO_DATE('20-02-1992','DD-MM-YYYY'), 'Backend Engineer', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Valeria', 'Guadalupe', 'Morales', 'Pineda', 29, 'F', TO_DATE('08-08-1996','DD-MM-YYYY'), 'UX Designer', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Pedro', 'Antonio', 'Ortiz', 'Camacho', 38, 'M', TO_DATE('25-12-1986','DD-MM-YYYY'), 'Site Reliability Engineer', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Daniela', 'Paola', 'Herrera', 'Quintana', 27, 'F', TO_DATE('03-04-1998','DD-MM-YYYY'), 'QA Automation', 0);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Miguel', 'Ángel', 'Castro', 'Domínguez', 31, 'M', TO_DATE('17-01-1994','DD-MM-YYYY'), 'Mobile Developer', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, SECOND_NAME, LAST_NAME, MOTHER_LAST_NAME, AGE, GENDER, BIRTH_DATE, POSITION, ACTIVE)
VALUES ('Ximena', 'Itzel', 'López', 'Barrera', 24, 'F', TO_DATE('14-06-2001','DD-MM-YYYY'), 'Intern', 1);